name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    env:
      DATABASE_URL=${DATABASE_URL}
      DATABASE_NAME=${DATABASE_NAME}
      DATABASE_NAME_TEST=${DATABASE_NAME_TEST}
      JWT_SECRET=ji=${JWT_SECRET}
      SERVER_ADDRESS=${SERVER_ADDRESS}
      CORS_ORIGINS=${CORS_ORIGINS}
